### ISSUE TITLE
Unexpected heavy Sagemaker docker for training with pytorch 2.0

### ISSUE THREAD

**Issue by falozzo** [aws/deep-learning-containers#3165]
Hi, 

I have noticed that the latest Sagemaker docker image for training using pytorch version 2.0.0 is much larger than its predecessors, even larger than 20 GB.

What is the reason for this increase in size? 
Is it really necessary for a Sagemaker training pipeline or is it possible to have lighter images in terms of size?

Thank you

**Comment by JamesB797** [comment]
Even the Huggingface CPU image is gigantic, I was expecting to be able to use it with sagemaker serverless, because I need transformers 4.28.1 at least to support pix2struct, but it's 13GB, which is already higher than the 10GB max size for sagemaker serverless.

```
763104351884.dkr.ecr.us-east-2.amazonaws.com/huggingface-pytorch-inference   2.0.0-transformers4.28.1-cpu-py310-ubuntu20.04         0c7309a82895   7 weeks ago     13.8GB
```

VS the previous version is only 4.3GB

```
763104351884.dkr.ecr.us-east-2.amazonaws.com/huggingface-pytorch-inference   1.13.1-transformers4.26.0-cpu-py39-ubuntu20.04         4c5aa6de61b0   13 days ago     4.31GB
```

I definitely need some form of solution for this, but with the current state of things I'll probably need to prepare my own image somehow.

Thanks

**Comment by sirutBuasai** [comment]
We have made an effort to decrease our image size in this [PR](https://github.com/aws/deep-learning-containers/pull/3337).
PyTorch 2.1 DLC and later versions should have reduced image size.

Please note that PyTorch 2.0 DLC is not out of support and we recommend upgrading your DLC to later PyTorch versions. see [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#sagemaker-framework-containers-sm-support-only) for more information.
