### ISSUE TITLE
[bug] skip_cpu pytest marker fails on local test

### ISSUE THREAD

**Issue by ChaiBapchya** [aws/deep-learning-containers#661]
Checklist
- [x] I've prepended issue tag with type of change: [bug]
- [ ] (If applicable) I've attached the script to reproduce the bug
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] I'm using an existing DLC image listed here: https://docs.aws.amazon.com/deep-learning-containers/latest/devguide/deep-learning-containers-images.html
- [ ] I've built my own container based off DLC (and I've attached the code used to build my own image)

*Concise Description:*

Existing pytest marker skip_cpu doesn't handle the case of testing locally.

*DLC image/dockerfile:*
Any DLC image
*Current behavior:*
```
@pytest.mark.skip_cpu
def test_of_your_choice
```
Running this test locally
```
pytest -s -v -rP integration/local/test_<>.py::test_of_your_choice --docker-base-name <>.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training --tag <>
```
Result
```
SKIPPED
```

*Expected behavior:*
Instead of skipping the test altogether, run it on local [if instance has gpu]

*Additional context:*
If instance doesn't have gpu-support, then skipping is justified. But currently, it skips_cpu ends up skipping test on GPU-based instance.

As a result, for debugging locally, one has to omit/comment the pytest marker

**Comment by saimidu** [comment]
@ChaiBapchya Thanks for raising this issue.

This behavior is due to the `--processor <cpu/gpu/eia>` pytest option not being specified on the SM Local test.

When an image is tested using the SageMaker integration tests, `conftest.py` expects to know at least one of the following from a user input:
1. `--processor`, which defaults to `"cpu"`, and is directly configured onto the `processor` pytest fixture
2. `--instance-type`, which is configured onto the `instance_type` pytest fixture if given, without which the `instance_type` pytest fixture defaults to `"local"` or `"local_gpu"`.
3. `--py-version`, which defaults to the python-version of the pytest command used to run the test, and is directly configured onto the `py_version` pytest fixture.

When `instance_type` is undefined, it defaults to `"local"`, and when `processor` is undefined, it defaults to `"cpu"`. This caused the test you ran to be skipped, in the example above.

Therefore, the fix here is to run your test with the `--processor` option specified.
